# File Tree: savior_ims

**Generated:** 3/12/2026, 9:34:25 PM
**Root Path:** `d:\pg\web_app\savior_ims`

```
└── 📁 backend
    ├── 📁 src
    │   ├── 📁 controllers
    │   │   ├── 📄 category.controller.ts
    │   │   ├── 📄 inventory.controller.ts
    │   │   ├── 📄 size.controller.ts
    │   │   └── 📄 vendor.controller.ts
    │   ├── 📁 middlewares
    │   │   ├── 📄 auth.ts
    │   │   └── 📄 validate.ts
    │   ├── 📁 models
    │   │   ├── 📄 Category.ts
    │   │   ├── 📄 Product.ts
    │   │   ├── 📄 Role.ts
    │   │   ├── 📄 Size.ts
    │   │   ├── 📄 User.ts
    │   │   └── 📄 Vendor.ts
    │   ├── 📁 routes
    │   │   ├── 📄 category.routes.ts
    │   │   ├── 📄 inventory.route.js
    │   │   ├── 📄 size.routes.ts
    │   │   └── 📄 vendor.routes.ts
    │   ├── 📁 services
    │   │   ├── 📄 category.service.ts
    │   │   ├── 📄 product.service.ts
    │   │   ├── 📄 size.service.ts
    │   │   ├── 📄 user.service.ts
    │   │   └── 📄 vendor.service.ts
    │   └── 📁 validators
    │       ├── 📄 master.validator.ts
    │       └── 📄 product.validator.ts
    ├── ⚙️ .gitignore
    ├── 📝 README.md
    ├── 📄 bun.lock
    ├── 📄 index.ts
    ├── ⚙️ package.json
    └── ⚙️ tsconfig.json
```

---
*Generated by FileTree Pro Extension*